feat: Design document for performance benchmarking
intel-retail/documentation pull request #6
Opened 2023-09-12 15:43 UTC by brian-intel

## PR Checklist

- [ ] Added label to the Pull Request for easier discoverability and search
- [ ] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)
- [ ] No Employer Confidential details are added

## What requirement is this design document for?

#3 

## Anything the reviewer should know when reviewing this PR?

## If there are any other design Pull Requests or requirements, please link them here (i.e. intel-retail/automated-self-checkout )

None

2023-09-12 16:21 UTC, jim-wang-intel requested changes
some grammar fix and suggestions

2023-09-12 16:21 UTC, jim-wang-intel commented on Architecture/performance_benchmarking.md
> +The benchmark script is designed to help determine the performance needs for a specific pipeline profile. The
this paragraph is incomplete

2023-09-12 16:21 UTC, jim-wang-intel commented on Architecture/performance_benchmarking.md
> +For performance inputs we support RTSP, USB camera, Intel® RealSense™ Camera, and video files. For test consistency it is recommended to use a video loop with an RTSP stream. As an option a RTSP [Cam
```suggestion
For performance inputs we support RTSP video streaming, USB camera, Intel® RealSense™ Camera, and video files. For testing consistency it is recommended to use a video loop with an RTSP stream. As an option an RTSP [Camera Simulator](https://intel-retail.github.io/automated-self-checkout/run_camera_simulator.html) is provided with the performance script.
```

2023-09-12 16:21 UTC, jim-wang-intel commented on Architecture/performance_benchmarking.md
> +If looking for the maximum number of pipelines that are supported on a specific hardware SKU you can use the stream density parameter. By setting the `--stream_density` parameter to the desired frame
```suggestion
If looking for the maximum number of pipelines that are supported on a specific hardware SKU for a given target FPS,  you can use the stream density parameter. By setting the `--stream_density` parameter to the desired frames per second (FPS) the script will continue to create pipelines until the average pipelines FPS falls below the desired FPS. The scrip will provide a detailed log to show each pipeline FPS during the test run. This option provides a method for testing the top performance when introducing a new pipeline or hardware SKU.
```

2023-09-12 22:08 UTC, jim-wang-intel commented on Architecture/performance_benchmarking.md
> +For performance inputs we support RTSP video streams, USB camera, Intel® RealSense™ Camera, and video files. For longer benchmarking runs it's recommended to use a video loop with an RTSP stream for
sorry, i missed this one: 
```suggestion
For performance inputs we support RTSP video streams, USB camera, Intel® RealSense™ Camera, and video files. For longer benchmarking runs it's recommended to use a video loop with an RTSP stream for inference result consistency. As an option an RTSP [Camera Simulator](https://intel-retail.github.io/automated-self-checkout/run_camera_simulator.html) is provided with the performance script.
```

2023-09-12 22:36 UTC, jim-wang-intel approved these changes

2023-09-13 22:41 UTC, NeethuES-intel commented on Architecture/performance_benchmarking.md
> +To assist customers we will provide a set of performance Docker containers to measure the performance of their pipelines. The performance Docker containers will need to be supported on most modern In
```suggestion
To assist customers we will provide a set of performance Docker containers to measure the performance of their pipelines. The performance Docker containers will need to be supported on most modern Intel hardware. The output will also need to be formatted and presented to customers as a hardware recommendation.
```

2023-09-13 22:41 UTC, NeethuES-intel commented on Architecture/performance_benchmarking.md
> +For performance inputs we support RTSP video streams, USB camera, Intel® RealSense™ Camera, and video files. For longer benchmarking runs it's recommended to use a video loop with an RTSP stream for
```suggestion
For performance inputs we support RTSP video streams, USB camera, Intel® RealSense™ Camera, and video files. For longer benchmarking runs its' recommended to use a video loop with an RTSP stream for inference result consistency. As an option an RTSP [Camera Simulator](https://intel-retail.github.io/automated-self-checkout/run_camera_simulator.html) is provided with the performance script.
```

2023-09-13 22:41 UTC, NeethuES-intel commented on Architecture/performance_benchmarking.md
> +To make reading results easier a consolidation script has been provided. This script will work with a single or multiple runs of the specified number of pipelines. Details about this process are foun
```suggestion
To make reading results easier, a consolidation script has been provided. This script will work with a single or multiple runs of the specified number of pipelines. Details about this process are found in [Benchmark Specified Number of Pipelines](https://intel-retail.github.io/automated-self-checkout/pipelinebenchmarking.html#benchmark-specified-number-of-pipelines)
```

2023-09-13 22:41 UTC, NeethuES-intel commented on Architecture/performance_benchmarking.md
> +The stream density parameter can be used to find the maximum number of pipelines at a target frames per second (FPS) on a specific hardware SKU. By setting the `--stream_density` parameter to the des
```suggestion
The stream density parameter can be used to find the maximum number of pipelines at a target frames per second (FPS) on a specific hardware SKU. By setting the `--stream_density` parameter to the desired FPS the script will continue to create pipelines until the average pipelines FPS falls below the desired FPS. The script will provide a detailed log to show each pipeline FPS during the test run. This option provides a method for testing the top performance when introducing a new pipeline or hardware SKU.
```

2023-09-13 23:37 UTC, NeethuES-intel approved these changes

2023-09-14 00:02 UTC, merged